# .rubocop.yml
plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'Guardfile'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

  DisplayCopNames: true

Rails:
  Enabled: true

Layout/LineLength:
  Max: 250

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  IgnoredMethods: ['describe']
  Exclude:
    - 'spec/**/*'
  Max: 70

Metrics/MethodLength:
  Include:
    - "app/controllers/*"
    - "app/models/*"
  Max: 20
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/GuardClause:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'config/**/*.yml'
  - 'bin/*'
Style/Documentation:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: true
