name: CI/CD

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: medical_appointments_api_test
          POSTGRES_USER: alex
          POSTGRES_PASSWORD: password123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U alex -d medical_appointments_api_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'

    - name: Cache Ruby gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Cache Node modules (if koristiš JS pakete)
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Prepare test database
      env:
        PGHOST: localhost
        PGUSER: alex
        PGPASSWORD: password123
        PGDATABASE: medical_appointments_api_test
      run: |
        bin/rails db:create db:migrate RAILS_ENV=test

    - name: Run RSpec tests
      env:
        PGHOST: localhost
        PGUSER: alex
        PGPASSWORD: password123
        PGDATABASE: medical_appointments_api_test
        RAILS_ENV: test
      run: bundle exec rspec
